### ISSUE TITLE
Crash with CommandNotFoundError

### ISSUE THREAD

**Issue by ejbyne** [makersacademy/unixoid-challenge#29] opened 2015-02-18 11:59 UTC
```
Roberts-MacBook-Pro:temp rob$ unixoid-challenge
Submitting your results to Makers Academy...
Please enter your Github username:
RBGeomaticsRob
Please enter your Github password:
Submitting...
/Users/rob/.rvm/gems/ruby-2.2.0/gems/cocaine-0.5.5/lib/cocaine/command_line.rb:83:in `run': Cocaine::CommandNotFoundError (Cocaine::CommandNotFoundError)
	from /Users/rob/.rvm/gems/ruby-2.2.0/gems/unixoid-challenge-0.1.1/lib/unixoid/runner.rb:21:in `run'
	from /Users/rob/.rvm/gems/ruby-2.2.0/gems/unixoid-challenge-0.1.1/lib/unixoid/git.rb:39:in `add_remote'
	from /Users/rob/.rvm/gems/ruby-2.2.0/gems/unixoid-challenge-0.1.1/lib/unixoid/git.rb:21:in `submit'
	from /Users/rob/.rvm/gems/ruby-2.2.0/gems/unixoid-challenge-0.1.1/lib/unixoid/controller.rb:29:in `push_to_github'
	from /Users/rob/.rvm/gems/ruby-2.2.0/gems/unixoid-challenge-0.1.1/lib/unixoid/controller.rb:7:in `run'
	from /Users/rob/.rvm/gems/ruby-2.2.0/gems/unixoid-challenge-0.1.1/bin/unixoid-challenge:7:in `<top (required)>'
	from /Users/rob/.rvm/gems/ruby-2.2.0/bin/unixoid-challenge:23:in `load'
	from /Users/rob/.rvm/gems/ruby-2.2.0/bin/unixoid-challenge:23:in `<main>'
	from /Users/rob/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/rob/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by pitchinvasion** [comment] 2015-02-18 14:46
Duplicate of #28

**Closed by pitchinvasion** 2015-02-18 14:46 UTC
