### ISSUE TITLE
Installing Ruby Gem

### ISSUE THREAD

**Issue by robertpulson** [makersacademy/unixoid-challenge#26] opened 2015-01-09 22:16 UTC
I have completed the challenge, however am having trouble installing the ruby gem. 

Apparently I do not have write permission?!

**Comment by loris-fo** [comment] 2015-01-10 02:12
Same for me, I had to use sudo.

**Comment by robertpulson** [comment] 2015-01-10 10:29
What does that involve? Sounds like something from Breaking Bad... ;)

**Comment by loris-fo** [comment] 2015-01-10 12:12
I don't what was the problem for you but for me it was something like this:

ERROR:     While executing gem ... (Gem: :FilePermissionError)
        You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

I recommend you to install RVM which will help you to get around this problem, but if you can't then you can use the next command to install the gem:

$ sudo gem install -unixoid-challenge

I'd use this really carefully as sudo is really powerful but if you can't submit your answers to the challenge, use it.

**Comment by spike01** [comment] 2015-02-18 18:29
Closing this as the problem is with the underlying Ruby installation

**Closed by spike01** 2015-02-18 18:29 UTC
